apiVersion: v1
kind: Service
metadata:
  name: svc-libera-externo
spec:
  type: NodePort
  selector:
    app: svc-pod-label
  ports:
    - port: 80
      nodePort: 30000


# $ kubectl get node -o wide - para descobrir o IP externo do meu NodePort