apiVersion: v1
kind: Service
metadata:
  name: svc-pod
  labels:
    app: svc-pod-label
spec:
  type: ClusterIP
  selector:
    app: node-app
  ports:
    - port: 80










    
    # - protocol: TCP
      # targetPort: 80
      
  # 

  # ports:
  #   - port: 80 # neste caso o servico recebe indormações na porta 80 e acessa o pod pela porta 80
  #   # - port: 8081 # neste caso o servico recebe indormações na porta 8081 e acessa o pod pela porta 80
  #     # targetPort: 80 # a porta do container é a 80


# Aplicar o servico
# $ kubectl apply -f svc-pod.yaml
# $ kubectl delete -f svc-pod.yaml
# $ kubectl describe -f svc-pod.yaml
# $ kubectl get services # ou kubectl get svc
