apiVersion: v1
kind: Pod
metadata:
  name: pod-nodejs
  labels:
    app: label-pod-nodejs
spec:
  containers:
    - name: container-pod-nodejs
      image: didox/nodejs-image:latest
      ports:
        - containerPort: 3000


# $ kubectl apply -f pod-nodejs.yaml 
# $ kubectl describe -f pod-nodejs.yaml 
# $ kubectl delete -f pod-nodejs.yaml 