apiVersion: v1
kind: Service
metadata:
  name: nodeport-svc-pod-dotnet
spec:
  type: NodePort
  ports:
    - port: 80
      #targetPort: 80
      nodePort: 30001 # até 32767
  selector:
    app: label-pod-dotnet

# $ kubectl apply -f node-port-svc-pod-dotnet.yaml
# $ kubectl describe -f node-port-svc-pod-dotnet.yaml
# $ kubectl delete -f node-port-svc-pod-dotnet.yaml

# para pegar o IP interno para acessar
# $ kubectl get nodes -o wide 
# INTERNAL-IP 
