apiVersion: v1
kind: Service
metadata:
  name: node-podsite-svc-pod-1
spec:
  type: NodePort
  ports:
    - port: 80
      #targetPort: 80
      nodePort: 30000 # até 32767
  selector:
    app: label-podsite-1



# para pegar o IP interno para acessar
# $ kubectl get nodes -o wide 
# INTERNAL-IP 