apiVersion: v1
kind: Pod
metadata:
  name: podmysql-1
  labels:
    app: label-podmysql-1
spec:
  containers:
    - name: container-podmysql-1
      image: mysql:5.6
      ports:
        - containerPort: 3306
      envFrom:
      - configMapRef:
          name: db-configmap
  
  
      # # buscando do configmap
      # env:
      #   - name: "MYSQL_ROOT_PASSWORD"
      #     valueFrom:
      #       configMapKeyRef:
      #         name: db-configmap
      #         key: MYSQL_ROOT_PASSWORD
      #   - name: "MYSQL_DATABASE"
      #     valueFrom:
      #       configMapKeyRef:
      #         name: db-configmap
      #         key: MYSQL_DATABASE
      #   - name: "MYSQL_PASSWORD"
      #     valueFrom:
      #       configMapKeyRef:
      #         name: db-configmap
      #         key: MYSQL_PASSWORD

      # env manual
      # env:
      #   - name: "MYSQL_ROOT_PASSWORD"
      #     value: "danilotestekub"
      #   - name: "MYSQL_DATABASE"
      #     value: "validador_cpf"
      #   - name: "MYSQL_PASSWORD"
      #     value: "danilotestekub"

# $ kubectl exec -it -f imagem_com_db/podmysql_1.yaml  -- bash