apiVersion: v1
kind: Pod
metadata:
  name: podsite-1
  labels:
    app: label-podsite-1
spec:
  containers:
    - name: container-podsite-1
      image: nginx:latest
      ports:
        - containerPort: 80
      envFrom:
        - configMapRef:
          name: site-configmap
